version: "3.8"
services:
  app:
    build: .
    container_name: app_c
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: mysql_c
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./mysql:/var/db/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
